Loaded dependency [python3/3.9.10]: gcc/10.3.0-binutils-2.36.1
Loaded module: python3/3.9.10

Loading python3/3.9.10
  Loading requirement: gcc/10.3.0-binutils-2.36.1
Loaded module: cuda/11.6
Traceback (most recent call last):
  File "/zhome/34/9/181032/Deep-Learning/unet_train_noise.py", line 238, in <module>
    image = np.transpose(image, (1, 2, 0))  # If image shape is (3, 256, 256)
  File "/zhome/34/9/181032/Deep-Learning/.venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 655, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/zhome/34/9/181032/Deep-Learning/.venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
